install arping
install asdf
install bdw-gc
install cloc
install cmake
install cscope
install ctags
install direnv
install docker
install elixir
install erlang@17
install exercism
install fish
install flac
install gcc
install gcc@4.9
install gdk-pixbuf
install git
install graphicsmagick
install helm
install htop
install iproute2mac
install jemalloc
install derailed/k9s/k9s
install kops
install johanhaleby/kubetail/kubetail
install lame
install libde265
install libpcl
install lua@5.1
install makedepend
install minikube
install neovim
install nmap
install openssh
install packer
install pango
install pass
install postgresql
install postgresql@9.5
install pstree
install pwgen
install pyenv
install qt
install reattach-to-user-namespace
install redis
install ssh-copy-id
install terminal-notifier
install terraform@0.11
install the_silver_searcher
install tmux
install trash
install vim
install wget
install yarn
install zlib
